services:
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27007:27017"
    volumes:
      - ./mongodb:/data/db
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge